name: digitalshift.me
description: A blog about digital strategy and change
markdown: redcarpet
pygments: false
baseurl: http://digitalshift.me
paginate: 5
prose: 
    rooturl: '_posts'
    media: 'assets'
